### ISSUE TITLE
Improving testing performance

### ISSUE THREAD

**Issue by observingClouds** [mllam/neural-lam#100]
As mentioned at the last developer meeting on Jan 13th 2025 the test suite is quite slow and takes quite a lot of time.

One of the first ideas to potentially improve the performance was to reduce the size of the example dataset.

**Comment by observingClouds** [comment]
@matschreiner since we were talking about this today, one option before creating a new smaller test dataset would be to use the `coords_range` config attribute to select only a subsection of the sample dataset.

e.g. extend the following section in https://github.com/mllam/neural-lam/blob/main/tests/datastore_examples/mdp/danra_100m_winds/danra.datastore.yaml by the spatial coordinates
```
  coord_ranges:
    time:
      start: 1990-09-03T00:00
      end: 1990-09-04T00:00
      step: PT3H
```
https://github.com/mllam/mllam-data-prep/blob/99fad9199547f3f57c3eb885fad018c8ba834493/example.danra.yaml#L9-L13
